[build]
  base = "todos/frontend/todos"         # Path where Vite configuration and package.json are located
  command = "npm run build"              # Command to build your project
  publish = "todos/frontend/todos/dist"  # Directory where Vite outputs the build
